# Generated by Django 2.2b1 on 2019-02-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='logo',
        ),
    ]
